### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Hackmastr**

### CODE REVIEW

**Comment by Hackmastr** [comment]
If I forgot some file, tell me

**Comment by satoon101** [comment]
Thank you!  If you could, please also update the remaining files:
- ../core/leader.ini
- ../core/level.ini
- ../core/winner.ini
- ../included_plugins/gg_bombing_objective.ini
- ../included_plugins/gg_elimination.ini
- ../included_plugins/config/gg_bombing_objective.ini
- ../included_plugins/config/gg_deathmatch.ini
- ../included_plugins/config/gg_disable_objectives.ini
- ../included_plugins/config/gg_dissolver.ini
- ../included_plugins/config/gg_elimination.ini
- ../included_plugins/config/gg_hostage_objective.ini
- ../included_plugins/config/gg_turbo.ini

Once all files have been added, I will merge this request.

**Comment by Hackmastr** [comment]
@satoon101 they're already translated :+1:

**Comment by satoon101** [comment]
Ah, oops, sorry, I forgot I had used the old GunGame51 translations for files that already had them.  Thanks again!

**Pull request merged**
